language: python
services:
- docker
python:
- 3.6.7
install:
- make deps
script:
- make test
- make lint
- make docker_push
env:
  global:
    secure: Jy8qeIRJ2jc9s47b/6pjDaUuo4Y6+bGQdqjzCY48sTuNn3zkrKd7D0cG4R9ja0JvF7TyMYKLLT2K8Kmg0ES6ZPb0wWRZAnD3a2JE7E2vXKheRjxFzZLsdb934b/h5fE+Yvlj8KPY55jV9CXkrMx/jwT/0HmWGsMuImhk7wvsknTLnY4NQZT3Q1m0u4hYIWSOnGkWOIKYQ1TIf5DMgDv4IR91J9BN0Jwi8GnvkZzfeu+yMBALHzOiYyLXvWMJzzF6g3jcrCI8CCuXUMHf+wNpUJWgiNH44OxQhg42M1WYXbWrGVP0P5mwg+LrW3NM5B8hqe6MUphR43wjQdDMeSUJ80CahM/g8QcuGnbbP5bI0qacYYmiFIYdIu1SvHnYxhaSrBiwCAcUEzZhdf9SIX9aKgwyOsB68i8l/xwPHNlapMA8a3fnFdNGeWHPS66ff8E6jK4O+MW+4H5KNFEApHURE+krwB9ehogBMjHWGikIKHxfVOybjsT4FYUqxWJ+jECpHDStbKa64ygeIT3CG7n4llMg9rN2/+s2dQQaVd0G31IhwWbAnrNkEdFOKzg49TPkDYN5NNiQ0pIQL1RaJMHcHnsAfVJTCXSqsox6LLfQ9kCwmkU5T9yPy0RS2N+XWDaOArB/5AungKausft0qWygQ5Y5cMg9q5Mr6UD4C97eAEQ=
deploy:
  provider: heroku
  app: library-01
  api_key: ${HEROKU_API_KEY}